/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "meas_packet.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(meas_packet_message, meas_packet_message, AUTO)



